language: python
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- pip install twine
- docker pull $DOCKER_IMAGE
script:
- ./.travis/run.sh
env:
  global:
    secure: Ko5kC6I1EfnU35aLIJE0UL/6A/r5DQIrqWVW9DADFhG/kXUiZmzK4N4xVMJL34EW6cVSSHxMflOJAuESVcwo92CTi3YE/MUD170bV/KhhcHXbq8vku/V3Gw9SoOAQa8MfG59PgM40vJSTMX0uxBhbLB9laU6Z7Gu+/3FglV1PhE3zUEKi58T2bEHceheAtmUu6hWZBDwhqI1CW7UP2jN2g2WVuiowtBL+GWlt8VlfnWrc3SKdpQYnCGhNks0pm+4FaLsNUkhATYtd7hIjTAKvo1q5kfG0JaV5clI0WpD4rIyx6Xnj3m9ulYl5EOmh2uAaYW3T6ty4piDkxL7Q6lYgEXmzokWWt3cPMx0wgeBKOHlyurb2gkZfQzdC+aS/zEFMjBsHLCSpqhzfb4IdCrUlRNwTaxooausEpzU1dZH3snwfzFn4AEn4nHPF3AStivFrqPpWcBmP7waH7UGzRalg00j4tuGvN1X0LlQOi2URE20+X8WFyn0j0IpUMZ7wqCaSiMffbsVQdzbNiw5UmFtX7f2zH/hE8rOGEvEFiXQCcJgFSYAaVCatRgaqV00IJh5IlfrR2zyTNhC1p2EkklgvFhIzU0r+306F+7lCnj4qaIPvHKNGeT1QmAo3w/iOl2nIqcjwpjEl9Ke0Zdsk4P57Dbx5aufFpPay4EhWrPvpy4=
deploy:
  provider: pypi
  username: kehtnok
  password:
    secure: ggS2iclWDMZoeamely61BavvTeiCsIxriOUlFV9Uz07rjyHzjjV+qVPKTGnNYc2ktI7BFIdkCBl1Y2Vr3mjuOl/kBK5ZwWzvw31q91gEB+M15Rxlhw10ObmXpgMhekMXSTJQ9bk2jVn5UtSg4nkh2prFNrVT5Zq9TJbOaFegWWW4v/h8OQTuGjjhILunV6U8QAfCphuZBlW8fLnFCspc3/wyy5zpXNUocY99oISCtjdnayJUrXimgSCQn56VfLBi2sTAoTVES38u++eZr7t+gP0zvcX/jR2jPNuhqVG/yPYsQnXK0Ubms55vuzBKsSRnxPiNzChq/h1MxRJxanDsUfEwdKqu5dtW+GQ2+C9jJ/g5R/rZyWrZPk4Buf1gdAu2yPgyOkfNRdSJvLtPYkbyHl3uObB15ykRLdCZRqFj+Z96JGhXq9k2KEA5g+Hq54mfrQxEGgfdVWy54A7TzAe64h2WdEJNQwwJLcJSLp3A/VSgYnDS89Tcq2yRtoAau0QPC3Q4RLN2KYJNjI+sSk4bt7Ds8joAdpdkHkxDdmLEBMM5eFCbpxY25IZGolhk7ITNtU9/fVgoFhl9Nl9bev4kc1zgts/68YsN5dUHYwAT+QaHz6vZVe8PUM1fJQ4thTYUBswCceA4+2z/aQ66SvdGx0viQDAoshGsxRW+KIT3nDg=
  on:
    tags: true
